<?php declare(strict_types=1);

/**
 * Copyright (C) Brian Faust
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cline\SSO\Exceptions;

/**
 * Exception thrown when a SAML response declares a destination that does not
 * match the package callback endpoint.
 *
 * Destination validation ensures the response was issued specifically for the
 * ACS URL generated by this package instance. A mismatch indicates the
 * identity provider is posting to the wrong callback URL or the response has
 * been replayed or redirected unexpectedly, so login processing must stop
 * before any identity claims are trusted.
 *
 * @author Brian Faust <brian@cline.sh>
 */
final class InvalidSamlDestinationException extends SamlException
{
    /**
     * Create an exception for a response with an unexpected destination.
     *
     * The factory is used after the XML has been parsed and the response
     * destination extracted, but before the assertion is accepted as being
     * intended for this application callback.
     */
    public static function create(): self
    {
        return new self(self::translate('sso::sso.saml.errors.invalid_destination'));
    }
}
