<?php declare(strict_types=1);

/**
 * Copyright (C) Brian Faust
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cline\SSO\Exceptions;

/**
 * Exception thrown when a SAML subject confirmation recipient does not match
 * the callback URL generated by the package.
 *
 * Recipient validation is specific to bearer subject confirmation and ensures
 * the assertion was minted for this service provider endpoint, not merely for
 * some broader SSO flow. This exception isolates that failure so it remains
 * distinguishable from response-destination mismatches or request-binding
 * problems elsewhere in the SAML trust chain.
 *
 * @author Brian Faust <brian@cline.sh>
 */
final class InvalidSamlRecipientException extends SamlException
{
    /**
     * Create an exception for a subject confirmation recipient mismatch.
     *
     * The factory is called once the package has resolved the expected
     * callback URL and compared it to the assertion's recipient attribute,
     * signalling that the bearer assertion should not be trusted for this
     * application endpoint.
     */
    public static function create(): self
    {
        return new self(self::translate('sso::sso.saml.errors.invalid_recipient'));
    }
}
